package certkit

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"fmt"
)

// GenerateCSR creates a Certificate Signing Request that copies Subject, DNSNames,
// IPAddresses, and URIs from the given leaf certificate. If privateKey is nil,
// a new EC P-256 key is generated. Returns the PEM-encoded CSR and, if a key was
// auto-generated, its PEM-encoded PKCS#8 private key (empty string if caller provided the key).
func GenerateCSR(leaf *x509.Certificate, privateKey crypto.PrivateKey) (csrPEM string, keyPEM string, err error) {
	var signer crypto.Signer
	autoGenerated := false

	if privateKey != nil {
		var ok bool
		signer, ok = privateKey.(crypto.Signer)
		if !ok {
			return "", "", fmt.Errorf("private key does not implement crypto.Signer")
		}
	} else {
		key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		if err != nil {
			return "", "", fmt.Errorf("generating EC P-256 key: %w", err)
		}
		signer = key
		autoGenerated = true
	}

	template := &x509.CertificateRequest{
		Subject:     leaf.Subject,
		DNSNames:    leaf.DNSNames,
		IPAddresses: leaf.IPAddresses,
		URIs:        leaf.URIs,
	}

	csrDER, err := x509.CreateCertificateRequest(rand.Reader, template, signer)
	if err != nil {
		return "", "", fmt.Errorf("creating CSR: %w", err)
	}

	csrPEM = string(pem.EncodeToMemory(&pem.Block{
		Type:  "CERTIFICATE REQUEST",
		Bytes: csrDER,
	}))

	if autoGenerated {
		keyDER, err := x509.MarshalPKCS8PrivateKey(signer)
		if err != nil {
			return "", "", fmt.Errorf("encoding private key: %w", err)
		}
		keyPEM = string(pem.EncodeToMemory(&pem.Block{
			Type:  "PRIVATE KEY",
			Bytes: keyDER,
		}))
	}

	return csrPEM, keyPEM, nil
}
